---
title: "Data_Changeover"
author: "Jain_Tarash"
date: ""
output: html_document
---

```{r Importing Libraries}
library(shiny)
library(dplyr)
library(ggplot2)
```

```{r Loading Data}
dataset1 <- read.csv('Population_2019.csv')
dataset2 <- read.csv('Covid_data.csv')
dataset3 <- NULL
```


```{r Dashboard}
ui <- fluidPage(
titlePanel('Data_ChangeOver'),
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = 'choice',
                  label = "Select the Data",  
                  choices = c("World Popultaion Trends","Covid-19 Trends", "Dataset3"),
                  selected = NULL,  multiple = FALSE,  selectize =TRUE,  
                  width = '300px'),
      
      conditionalPanel(
        condition = "input.choice == 'World Popultaion Trends'",
        sliderInput(inputId = "year",
                  label = "Select the year",
                  1950, 2100, 1,
                  value = 1950,
                  width = '300px',
                  animate = animationOptions(interval = .1,
                               playButton = icon('play', "fa-2x"),
                               pauseButton = icon('pause', "fa-2x"))),
                ),
      
      conditionalPanel(
        condition = "input.choice == 'Covid-19 Trends'",
        sliderInput(inputId = "covid_month",
                  label = "Select the Month",
                  18262, 18647, 4,
                  value = 0,
                  width = '300px',
                  animate = animationOptions(interval = .1,
                               playButton = icon('play', "fa-2x"),
                               pauseButton = icon('pause', "fa-2x"))),
                )
      ),

    mainPanel(
      # CODE BELOW: 
    textOutput("text_1"),
    plotOutput("plot", height = 600, width = 1000),
    textOutput("description")
    )
  )
)
```

```{r Server}


  server <- function(input, output, session) {
    
    ch = reactive(input$choice)
    if(as.ch == 'World Popultaion Trends'){
      output$plot <- renderPlot({
        input_year = input$year
        dataset1 %>% 
          filter(Variant == "Medium") %>% 
          filter(Time == input_year) %>% 
          top_n(10,PopTotal) %>% 
          mutate(Location = fct_reorder(Location, PopTotal))%>% 
          ggplot(aes(x = PopTotal, y = Location, fill = Location))+ 
          geom_col() +
          geom_text(aes(label=PopTotal), vjust=1.6, color="black", size=3.5)
      })
        output$text_1 <- renderText({
        paste("Year:",input$year)
        })
       output$description <- renderText({
        paste('DataSource')
        })
    }
    
  else if (ch == 'Covid-19 Trends'){
  output$plot <- renderPlot({
    input_covidmonth = input$covid_month
    dataset2 %>% 
      filter(location != 'World') %>%
      filter(location != 'International') %>%
      mutate(date_num = as.numeric(as.Date(date))) %>% 
      filter(date_num == input_covidmonth) %>% 
      top_n(10,total_cases) %>% 
      mutate(location = fct_reorder(location, total_cases)) %>% 
      ggplot(aes(x = total_cases, y = location, fill = location))+ 
      geom_col() +
        geom_text(aes(label=total_cases), vjust=1.6, color="black", size=3.5)
    
    })
      output$text_1 <- renderText({
      paste("Date:",as.Date(input$covid_month, origin = "1970-01-01"))
        })
     output$description <- renderText({
      paste('https://ourworldindata.org/coronavirus-source-data')
      })
    
    
    }
}
```


```{r}
server <- function(input, output, session) {
  output$plot <- renderPlot({
    input_covidmonth = input$covid_month
    dataset2 %>% 
      filter(location != 'World') %>%
      filter(location != 'International') %>%
      mutate(date_num = as.numeric(as.Date(date))) %>% 
      filter(date_num == input_covidmonth) %>% 
      top_n(10,total_cases) %>% 
      mutate(location = fct_reorder(location, total_cases)) %>% 
      ggplot(aes(x = total_cases, y = location, fill = location))+ 
      geom_col() +
        geom_text(aes(label=total_cases), vjust=1.6, color="black", size=3.5)
    
    })
      output$text_1 <- renderText({
      paste("Date:",as.Date(input$covid_month, origin = "1970-01-01"))
        })
     output$description <- renderText({
      paste('https://ourworldindata.org/coronavirus-source-data')
      })

}
```




```{r App}
shinyApp(ui, server)
```

